---
- name: install gnome-keyring
  pacman: name=gnome-keyring
  become: yes
- name: install libgnome-keyring
  pacman: name=libgnome-keyring
  become: yes
- name: compile helper
  debug: msg="cd /usr/share/git/credential/gnome-keyring && sudo make"
