---
- name: install tint2
  pacman: name=tint2
  become: yes
- name: clone my git repository
  git: repo=https://github.com/suzuki-shunsuke/tint2.conf
       dest={{home}}/.config/tint2
       update=no
