---
- name: install tint2
  pacman: name=tint2
  become: yes
- name: make symbolic link to tint2
  file: src={{ghq_root}}/github.com/suzuki-shunsuke/tint2.conf
        dest={{home}}/.config/tint2
        state=link
