---
- name: mkdir .vimundo
  file: path={{home}}/.vimundo state=directory
- name: make symbolic link to .vim
  file: src={{ghq_root}}/github.com/suzuki-shunsuke/vim.conf/.vim
        dest={{home}}/.vim
        state=link
- name: make symbolic link to .vimrc
  file: src={{ghq_root}}/github.com/suzuki-shunsuke/vim.conf/.vimrc
        dest={{home}}/.vimrc
        state=link
- name: make symbolic link to NeoBundle
  file: src={{ghq_root}}/github.com/Shougo/neobundle.vim
        dest={{ghq_root}}/github.com/suzuki-shunsuke/vim.conf/.vim/bundle/neobundle.vim
        state=link
