---
- name: make symbolic links
  file: src={{ghq_root}}/github.com/{{item.src}}
        dest={{home}}/{{item.dest}}
        state=link
  with_items:
    - { src: suzuki-shunsuke/zsh.conf/.zshrc, dest: .zshrc }
    - { src: b4b4r07/zplug, dest: .zplug }
    - { src: suzuki-shunsuke/zsh.conf, dest: .zsh }
- name: install zsh
  pacman: name=zsh
  become: yes
- name: change the default shell to zsh
  user: name={{ansible_env.USER}} shell=/usr/bin/zsh
  become: yes
