---
- name: mkdir
  file: path={{ghq_root}}/github.com/junegunn
        state=directory
- name: clone fzf repository
  git: repo=https://github.com/junegunn/fzf
       dest={{ghq_root}}/junegunn/fzf update=no
