---
- name: mkdir
  file: path={{ghq_root}}/github.com/suzuki-shunsuke
        state=directory
- name: clone my git repository
  git: repo=https://github.com/suzuki-shunsuke/git.conf
       dest={{ghq_root}}/github.com/suzuki-shunsuke/git.conf
       update=no
- name: make symbolic link to .gitconfig
  file: src={{ghq_root}}/github.com/suzuki-shunsuke/git.conf/.gitconfig
        dest={{home}}/.gitconfig
        state=link
