---
- name: mkdir
  file: path={{ghq_root}}/github.com/suzuki-shunsuke
        state=directory
- name: mkdir
  file: path={{ghq_root}}/github.com/tmux-plugins
        state=directory
- name: install tmux
  pacman: name=tmux
  become: yes
- name: clone tmux config repository
  git: repo=https://github.com/suzuki-shunsuke/tmux.conf
       dest={{ghq_root}}/github.com/suzuki-shunsuke/tmux.conf
       update=no
- name: clone tpm
  git: repo=https://github.com/tmux-plugins/tpm
       dest={{ghq_root}}/github.com/tmux-plugins/tpm
       update=no
- name: make symbolic link(.tmux.conf)
  file: src={{ghq_root}}/github.com/tmux-plugins/tpm
        dest={{ghq_root}}/github.com/suzuki-shunsuke/tmux.conf/plugins/tpm
        state=link
- name: make symbolic link(.tmux.conf)
  file: src={{ghq_root}}/github.com/suzuki-shunsuke/tmux.conf/.tmux.conf
        dest={{home}}/.tmux.conf
        state=link
