---
- name: install openbox
  pacman: name=openbox
  become: yes
- name: make symbolic link to openbox
  file: src={{ghq_root}}/github.com/suzuki-shunsuke/openbox.conf
        dest={{home}}/.config/openbox
        state=link
