---
- name: mkdir {{home}}/.config
  file: path={{home}}/.config
        state=directory
- name: make symbolic link to fontconfig
  file: src={{ghq_root}}/github.com/suzuki-shunsuke/font.conf
        dest={{home}}/.config/fontconfig
        state=link
