---
- name: mkdir
  file: path={{ghq_root}}/github.com/suzuki-shunsuke
- name: clone my git repository
  git: repo=https://github.com/suzuki-shunsuke/font.conf
       dest={{ghq_root}}/github.com/suzuki-shunsuke/font.conf
       update=no
- name: make symbolic link to fontconfig
  file: src={{ghq_root}}/github.com/suzuki-shunsuke/font.conf
        dest={{home}}/.config/fontconfig
        state=link
